### ISSUE TITLE
samples from samplesheet.yml are not reported

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#92]
This might be an issue with an older version (analyses was run end of February). 

Samples that are given in the samplesheet.yml and yield no reads in demultiplexing are not reported in output. this may lead to missing information in tracking samples further downstream. 

could you add the information of lacking reads in a report.csv or similar?

**Comment by replikation** [comment]
* should be doable if a sample input file is provided.

**Comment by hoelzer** [comment]
> * should be doable if a sample input file is provided.

Yes exactly, we would specifically need this in case a sample sheet is provided. It would be sufficient to add samples missing in the final output (bc/ no consensus was constructed) to the report (HTML, XLSX, {C,T}SV) - e.g. a row that just has the ID and all other columns are 'NA' or something like 'No consensus reconstructed due to low read amount'.

I was thinking about how to add this but I think w/ some channel magic you are faster, @replikation ? :)

**Comment by RaverJay** [comment]
On it
