### ISSUE TITLE
Provide `--fastq_pass` AND `--fast5` to`--nanopolish`

### ISSUE THREAD

**Issue by iferres** [replikation/poreCov#94]
Hi, me again. Thanks for your updates! 

I have a request, I hope it make sense to you. Would it be possible to provide both fast5 and fastq to the nanopolish workflow, but avoid basecalling? I basecalled the fast5 in a different platform from where I'm launching poreCov, so I have both types of files already. I have gpu in the former but no in the latter. 

I notice that if I provide fast5, then poreCov asumes it has to basecall them, am I right? May be providing both could avoid the basecalling step and go directly to nanopolish. 

If you think it makes sense but don't have the time, I could try to implement it and fill a PR. Let me know!

**Comment by replikation** [comment]
hi, thanks for the suggestion,

seems indeed like a good choice and sounds reasonable. i have a general idea how to implement it cleanly into poreCov so that the appropriate workflows are executed automatically. ill open a branch, add the code, and ill ping you for some testing on my PR if you like?

**Comment by iferres** [comment]
Great! Thanks!

**Comment by replikation** [comment]
@iferres any suggestions on the sequencing summary file? as it is not inside the fastq pass dir.

**Comment by iferres** [comment]
Yes, may be passing it at the CLI as flag, as in: https://github.com/connor-lab/ncov2019-artic-nf . They use `--sequencing_summary`. What do you think?
